version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Mattis6666"
      - "Naia-love"
      - "Remty5"
    labels:
      - "dependencies"
