language: node_js
node_js:
    - '13.6.0'
cache:
    npm: false
    directories:
        - ./.yarn/cache

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn -v

install: yarn
